require:
  - rubocop-performance
#  - rubocop-rspec
  - rubocop-rails
#  - rubocop-capybara
#  - rubocop-factory_bot

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.1

Rails/I18nLocaleTexts:
  Enabled: false
  
Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false
  
Style/ClassVars:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 11