require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.1

Rails/I18nLocaleTexts:
  Enabled: false
  
Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false
  
Style/ClassVars:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 11

Layout/LineLength:
  Max: 125

Capybara/ClickLinkOrButtonStyle:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/ExampleLength:
  Max: 6

RSpec/DescribeMethod:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 2

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/FilePath:
  Enabled: false
